/** The licences of the Go modules compiled into the agents:
 *  `bun run licenses` writes them into THIRD-PARTY-LICENSES.md,
 *  `bun run licenses -- --check` fails when that file is out of date.
 *
 *  The agents are distributed as binaries, and the BSD and MIT licences of what
 *  they link ask that the notice travel with the binary. So the notice is
 *  generated from the modules the build actually uses — `go list -deps` on each
 *  agent — rather than kept by hand, where it would lose a dependency the first
 *  time one was added. Test-only modules (the fake Kafka broker) are not linked
 *  into anything shipped and are not listed.
 *
 *  The section sits between two markers; everything else in the file is left
 *  alone.
 */
import { readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { findGo, GO_MISSING } from "./go-toolchain.ts";

const FILE = "THIRD-PARTY-LICENSES.md";
const BEGIN = "<!-- go-licenses:begin -->";
const END = "<!-- go-licenses:end -->";
const AGENTS = ["code-agent-go", "kafka-agent-go"];

interface Mod {
  path: string;
  version: string;
  dir: string;
  agents: Set<string>;
}

const go = await findGo();
if (!go) throw new Error(GO_MISSING);

const mods = new Map<string, Mod>();
for (const agent of AGENTS) {
  const proc = Bun.spawn([go, "list", "-deps", "-f", "{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}", "."], {
    cwd: agent,
    stdout: "pipe",
    stderr: "inherit",
    stdin: "ignore",
  });
  const out = await new Response(proc.stdout).text();
  if ((await proc.exited) !== 0) throw new Error(`go list failed in ${agent}`);
  for (const line of out.split("\n")) {
    const [path, version, dir] = line.trim().split("|");
    if (!path || !dir || path.startsWith("enc-tool/")) continue;
    const key = `${path}@${version}`;
    const m = mods.get(key) ?? { path, version, dir, agents: new Set() };
    m.agents.add(agent.replace(/-go$/, ""));
    mods.set(key, m);
  }
}

async function licenceOf(dir: string): Promise<string> {
  const names = (await readdir(dir)).filter((n) => /^(LICEN[CS]E|COPYING)(\.(md|txt))?$/i.test(n));
  if (!names.length) throw new Error(`no licence file in ${dir}`);
  return (await readFile(join(dir, names[0]), "utf8")).replace(/\r\n/g, "\n").trim();
}

const sorted = [...mods.values()].sort((a, b) => a.path.localeCompare(b.path));
let section = `${BEGIN}
## Go modules compiled into the agents

Generated by \`bun run licenses\` from \`go list -deps\` of each agent — do not edit
by hand; \`bun run audit\` fails when it is out of date.

`;
for (const m of sorted) {
  section += `### ${m.path} ${m.version}\n\nUsed by: ${[...m.agents].sort().join(", ")}\n\n\`\`\`\n${await licenceOf(m.dir)}\n\`\`\`\n\n`;
}
section += END;

const current = await readFile(FILE, "utf8");
const at = current.indexOf(BEGIN);
const to = current.indexOf(END);
const next =
  at >= 0 && to > at
    ? current.slice(0, at) + section + current.slice(to + END.length)
    : `${current.trimEnd()}\n\n---\n\n${section}\n`;

if (process.argv.includes("--check")) {
  if (next.replace(/\r\n/g, "\n") !== current.replace(/\r\n/g, "\n")) {
    console.error(`${FILE} is out of date — run: bun run licenses`);
    process.exit(1);
  }
  console.log(`${FILE} is up to date (${sorted.length} Go modules)`);
} else {
  await writeFile(FILE, next);
  console.log(`wrote ${sorted.length} Go module licences to ${FILE}`);
}
