/** Assets imported with `{ type: "file" }` resolve to a path string at runtime
 *  (and are embedded by `bun build --compile`); TypeScript needs to be told
 *  their shape or every such import is an unresolved module. */
declare module "*.png" {
  const path: string;
  export default path;
}

declare module "*.webmanifest" {
  const path: string;
  export default path;
}

/** The built bundles under public/. They are generated by `bun run build`, so
 *  TypeScript cannot see them in a clean checkout — and @types/bun would type
 *  the .html entry as an HTMLBundle, which is what `with { type: "file" }`
 *  specifically opts out of. Relative names are illegal in an ambient module
 *  declaration, hence the leading wildcard. */
declare module "*/public/main.js" {
  const path: string;
  export default path;
}
declare module "*/public/main.css" {
  const path: string;
  export default path;
}
declare module "*/public/code.js" {
  const path: string;
  export default path;
}
declare module "*/public/sw.js" {
  const path: string;
  export default path;
}
declare module "*/web/index.html" {
  const path: string;
  export default path;
}
